# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cell.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cell(object):
    def setupUi(self, Cell):
        Cell.setObjectName("Cell")
        Cell.setWindowModality(QtCore.Qt.NonModal)
        Cell.resize(116, 80)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Cell.sizePolicy().hasHeightForWidth())
        Cell.setSizePolicy(sizePolicy)
        Cell.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(Cell)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button = QtWidgets.QPushButton(Cell)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.button.setFont(font)
        self.button.setAutoFillBackground(False)
        self.button.setText("")
        self.button.setAutoDefault(False)
        self.button.setDefault(False)
        self.button.setFlat(False)
        self.button.setObjectName("button")
        self.gridLayout.addWidget(self.button, 0, 0, 1, 1)

        self.retranslateUi(Cell)
        QtCore.QMetaObject.connectSlotsByName(Cell)

    def retranslateUi(self, Cell):
        _translate = QtCore.QCoreApplication.translate
        Cell.setWindowTitle(_translate("Cell", "Form"))
