# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_mode_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameModeItem(object):
    def setupUi(self, GameModeItem):
        GameModeItem.setObjectName("GameModeItem")
        GameModeItem.resize(360, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(GameModeItem)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_btn = QtWidgets.QPushButton(GameModeItem)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.select_btn.setFont(font)
        self.select_btn.setStyleSheet("padding: 10px;")
        self.select_btn.setText("")
        self.select_btn.setObjectName("select_btn")
        self.verticalLayout.addWidget(self.select_btn)
        self.description_label = QtWidgets.QLabel(GameModeItem)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.description_label.setFont(font)
        self.description_label.setStyleSheet("")
        self.description_label.setText("")
        self.description_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.description_label.setWordWrap(True)
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)

        self.retranslateUi(GameModeItem)
        QtCore.QMetaObject.connectSlotsByName(GameModeItem)

    def retranslateUi(self, GameModeItem):
        _translate = QtCore.QCoreApplication.translate
        GameModeItem.setWindowTitle(_translate("GameModeItem", "Form"))
