# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_mode_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameModeSelectScreen(object):
    def setupUi(self, GameModeSelectScreen):
        GameModeSelectScreen.setObjectName("GameModeSelectScreen")
        GameModeSelectScreen.resize(360, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GameModeSelectScreen.sizePolicy().hasHeightForWidth())
        GameModeSelectScreen.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(GameModeSelectScreen)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.mode_select_label = QtWidgets.QLabel(GameModeSelectScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.mode_select_label.sizePolicy().hasHeightForWidth())
        self.mode_select_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.mode_select_label.setFont(font)
        self.mode_select_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.mode_select_label.setObjectName("mode_select_label")
        self.main_layout.addWidget(self.mode_select_label)
        self.game_modes = QtWidgets.QWidget(GameModeSelectScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.game_modes.sizePolicy().hasHeightForWidth())
        self.game_modes.setSizePolicy(sizePolicy)
        self.game_modes.setObjectName("game_modes")
        self.game_modes_layout = QtWidgets.QVBoxLayout(self.game_modes)
        self.game_modes_layout.setContentsMargins(0, 0, 0, 0)
        self.game_modes_layout.setSpacing(10)
        self.game_modes_layout.setObjectName("game_modes_layout")
        self.main_layout.addWidget(self.game_modes)
        self.go_back_btn = QtWidgets.QPushButton(GameModeSelectScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.go_back_btn.sizePolicy().hasHeightForWidth())
        self.go_back_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.go_back_btn.setFont(font)
        self.go_back_btn.setStyleSheet("padding: 10px;")
        self.go_back_btn.setObjectName("go_back_btn")
        self.main_layout.addWidget(self.go_back_btn)
        self.gridLayout.addLayout(self.main_layout, 0, 0, 1, 1)

        self.retranslateUi(GameModeSelectScreen)
        QtCore.QMetaObject.connectSlotsByName(GameModeSelectScreen)

    def retranslateUi(self, GameModeSelectScreen):
        _translate = QtCore.QCoreApplication.translate
        GameModeSelectScreen.setWindowTitle(_translate("GameModeSelectScreen", "MetChars - Выбор режима игры"))
        self.mode_select_label.setText(_translate("GameModeSelectScreen", "Выберите режим"))
        self.go_back_btn.setText(_translate("GameModeSelectScreen", "Вернуться назад"))
