# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'players.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayersScreen(object):
    def setupUi(self, PlayersScreen):
        PlayersScreen.setObjectName("PlayersScreen")
        PlayersScreen.resize(360, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlayersScreen.sizePolicy().hasHeightForWidth())
        PlayersScreen.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(PlayersScreen)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.header_label = QtWidgets.QLabel(PlayersScreen)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setStyleSheet("padding: 5px;")
        self.header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.main_layout.addWidget(self.header_label)
        self.create_player_btn = QtWidgets.QPushButton(PlayersScreen)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.create_player_btn.setFont(font)
        self.create_player_btn.setStyleSheet("padding: 5px;")
        self.create_player_btn.setObjectName("create_player_btn")
        self.main_layout.addWidget(self.create_player_btn)
        self.players_scroll_area = QtWidgets.QScrollArea(PlayersScreen)
        self.players_scroll_area.setStyleSheet("QScrollArea { border: none; }")
        self.players_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.players_scroll_area.setWidgetResizable(True)
        self.players_scroll_area.setObjectName("players_scroll_area")
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 358, 496))
        self.scroll_area_widget_contents.setObjectName("scroll_area_widget_contents")
        self.players_layout = QtWidgets.QVBoxLayout(self.scroll_area_widget_contents)
        self.players_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.players_layout.setContentsMargins(0, 0, 0, 0)
        self.players_layout.setObjectName("players_layout")
        self.players_scroll_area.setWidget(self.scroll_area_widget_contents)
        self.main_layout.addWidget(self.players_scroll_area)
        self.go_back_btn = QtWidgets.QPushButton(PlayersScreen)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.go_back_btn.setFont(font)
        self.go_back_btn.setStyleSheet("padding: 5px;")
        self.go_back_btn.setObjectName("go_back_btn")
        self.main_layout.addWidget(self.go_back_btn)
        self.gridLayout.addLayout(self.main_layout, 0, 0, 1, 1)

        self.retranslateUi(PlayersScreen)
        QtCore.QMetaObject.connectSlotsByName(PlayersScreen)

    def retranslateUi(self, PlayersScreen):
        _translate = QtCore.QCoreApplication.translate
        PlayersScreen.setWindowTitle(_translate("PlayersScreen", "MetChars - Игроки"))
        self.header_label.setText(_translate("PlayersScreen", "Игроки"))
        self.create_player_btn.setText(_translate("PlayersScreen", "Создать игрока"))
        self.go_back_btn.setText(_translate("PlayersScreen", "Вернуться назад"))
